apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-admin-server
  labels:
    app: spring-petclinic-admin-server
spec:
  clusterIP: None
  selector:
    app: spring-petclinic-admin-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-admin-server
  labels:
    app: spring-petclinic-admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic-admin-server
  template:
    metadata:
      labels:
        app: spring-petclinic-admin-server
    spec:
      containers:
      - name: spring-petclinic-admin-server
        image: spring-petclinic-admin-server
